# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_newslink_unique_together_slug_startup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='tags',
            field=models.ManyToManyField(to='organizer.Tag', blank=True),
        ),
    ]
